# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QuizChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizChallenge

  target 'QuizChallengeTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end

  target 'QuizChallengeUITests' do
    inherit! :search_paths
    pod 'KIF'
  end

end
