# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'QuizChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizChallenge

  target 'QuizChallengeTests' do
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
    
    target 'QuizChallengeKIFTests' do
      pod 'KIF', '~> 3.7.4'
      pod 'KIF-Quick'
    end
  end
  
end
